---
- hosts: directorio:archivo
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
    - name: crear directorio destino
      file:
        path: "{{ remote_dir }}"
        state: directory
        recurse: yes

    
    - name: copiar facts
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
