---
- hosts: grupo2
  become: true
  tasks:
    - name: crear archivo
      copy:
        content: "123"
        dest: /root/123.txt
      register: file
    - name: debug
      debug:
        var: file

# Con register declaramos a file como una variable y con el modulo debug invocamos la variable
